In [1]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from nltk.tokenize import word_tokenize
from sklearn.naive_bayes import GaussianNB
import sys

In [2]:
data = pd.read_csv("Freqs/F.csv", delimiter = '\t', header = 1)

In [3]:
data

         Unnamed: 0
NaN NaN         NaN
    NaN         NaN
    NaN         NaN
    NaN         NaN
    NaN         NaN
    NaN         NaN
    NaN         NaN
    NaN         NaN
    NaN         NaN
    NaN         NaN
    NaN         NaN
    NaN         NaN
    NaN         NaN
    NaN         NaN
    NaN         NaN
    NaN         NaN
    NaN         NaN
    NaN         NaN
    NaN         NaN
    NaN         NaN
    NaN         NaN
    NaN         NaN
    NaN         NaN
    NaN         NaN
    NaN         NaN
    NaN         NaN
    NaN         NaN
    NaN         NaN
    NaN         NaN
    NaN         NaN
...             ...
    NaN         NaN
    NaN         NaN
    NaN         NaN
    NaN         NaN
    NaN         NaN
    NaN         NaN
    NaN         NaN
    NaN         NaN
    NaN         NaN
    NaN         NaN
    NaN         NaN
    NaN         NaN
    NaN         NaN
    NaN         NaN
    NaN         NaN
    NaN         NaN
    NaN         NaN
    NaN         NaN
    NaN         NaN
    NaN         NaN
    NaN         NaN
    NaN         NaN
    NaN         NaN
    NaN         NaN
    NaN         NaN
    NaN         NaN
    NaN         NaN
    NaN         NaN
    NaN         NaN
    NaN         NaN

[4957 rows x 1 columns]

In [10]:
data = pd.read_excel("Freqs/Frequencies.xlsx", sheetname=2, header=0)

In [11]:
data

           Word  Samanta  Meduza
0             а       28       5
1        аварии        0       2
2         автор        0       2
3       адвокат        0       2
4         акция        0       2
5     александр        0       2
6      артистов        0       2
7          бабы        5       0
8         барак        0       2
9           без        3       2
10     близнецы        4       0
11        блять        3       0
12     боевиков        0       2
13       бойцов        0       2
14        более        0       4
15       больше        0       4
16        будет        1       4
17        будто        2       0
18        будут        0       3
19           бы        6       1
20       бывший        2       2
21         была        3       1
22         было        6       1
23         быть       14       1
24            в       53      91
25     валентин        2       0
26          вам        3       0
27          вас        1       3
28    вернуться        2       0
29         весы        4       0
..          ...      ...     ...
462      четыре        0       3
463       чечне        0       3
464      чтении        0       2
465         что       36      17
466      что-то        3       1
467        чтоб        2       0
468       чтобы       13       4
469  чувствуешь        2       0
470  школьников        0       2
471      штрафы        0       2
472         эти        5       0
473         это       17       1
474         это       17       1
475       этого        2       0
476        этой        2       0
477        этот        4       0
478       эфира        0       2
479           я       39       1
480        язык        2       0
481      января        0       3
482      япония        0       2
483  alihundred        7       0
484      amazon        0       2
485         cnn        0       2
486      falcon        0       2
487    nintendo        0       2
488    shapi_to        0       5
489      switch        0       2
490         the        0       3
491          xx        0       2

[492 rows x 3 columns]

In [ ]:
print (5*2)
import scipy as sp
data = sp.gen